Add ACP for camosslimageproxy
phpbb-extensions/camosslimageproxy pull request #6
Opened 2016-11-03 20:21 UTC by v12mike

I have tested this code on a live forum for a couple of weeks, and it seems to be stable.

2016-11-27 22:47 UTC, v12mike commented
I added a 'license.txt' (note spelling) because the phpbb extension pre-validation script requires it.  I am unfamiliar with any GitHub requirements, or which takes precedence.

2016-12-11 04:55 UTC, DavidIQ commented
@michaelcullum or @VSEphpbb think one of you could give this a look and review? Thanks.

2016-12-11 14:15 UTC, michaelcullum requested changes

2016-12-11 14:15 UTC, michaelcullum commented on camosslimageproxy_module.php
> +<?php
What is this file?

2016-12-11 14:15 UTC, michaelcullum commented on config/services.yml
> +
Please only have one new line at EOF.

2016-12-11 14:15 UTC, michaelcullum commented on event/listener.php
> +define('REGEX_STRING', '#<img [^>]*src="(http://[^"]+)"[^>]*>#'); //define it once here, in csse it needs adjusting
There's not really a reason to split this off and it makes the code harder to follow I'd say to be honest.

2016-12-11 14:15 UTC, michaelcullum commented on event/listener.php
> +						$object[$key] = str_replace($url, 'https://' . $this->config['camosslimageproxy_proxyaddress'] . '/' . $digest . '/' . bin2hex($url), $object[$key]);
Why the removals of src?

2016-12-11 14:15 UTC, michaelcullum commented on event/listener.php
> +								$this->unhandled_insecure_link(($key == '.')?'headers':$key, $field, $locations);
If a camo server goes down this is going to fill up way too quickly. I don't see a need to do this and camo going down or not accepting a url should fail quietly.. Unless this was going to be done using proper queuing and logging (like RabbitMQ) this has almost no benefit but plenty of downsides.

2016-12-11 14:15 UTC, michaelcullum commented on event/listener.php
> +	public function __construct(\phpbb\config\config $config, \phpbb\db\driver\driver_interface $db, $table_prefix, $auth, $user)
Constructor should be the first method

2016-12-11 14:15 UTC, michaelcullum commented on event/listener.php
> +		global $cache;
If you're adding constructors, why are you using globals still?

2016-12-11 14:15 UTC, michaelcullum commented on event/listener.php
>  		global $request;
These globals can go also as can the container references.

2016-12-11 14:15 UTC, michaelcullum commented on event/listener.php
> -		if (!$request->is_secure())
We should still be checking this?

2016-12-11 14:15 UTC, michaelcullum commented on event/listener.php
> +		$sql = 'SELECT location, field, core, location_id FROM ' . $this->table_prefix . 'camo_locations';
Locations can and should be hardcoded still I think? There is almost no advantage to having this configurable but it adds huge complexity.

2016-12-11 14:15 UTC, michaelcullum commented on event/listener.php
> +		$sql = 'SELECT location, field, core, location_id FROM ' . $this->table_prefix . 'camo_locations';
Although perhaps add an event so extensions can tap into it and rewrite their images also.

2016-12-11 14:15 UTC, michaelcullum commented on acp/camosslimageproxy_info.php
> +* @copyright (c) 2016 v12Mike
You're welcome to add yourself as an author but copyright does need to be to phpBB.

2016-12-11 14:15 UTC, michaelcullum commented on migrations/release_1_1_0.php
> +				'ACP_CAT_DOT_MODS',
Hm?

2016-12-11 14:25 UTC, michaelcullum commented
Sorry for taking so long to get to this

2016-12-11 22:30 UTC, Noxwizard commented on README.md
> +1. Add at least your sites domain(s) to the Directly Mapped Domains list (without protocol specifier or trailing /) e.g. mydomain.com
Looking at the code farther down, it looks like the intent may be if you are in control of several domains it can just change the http to https for all of those instead of routing them through the proxy.

2016-12-11 22:33 UTC, Noxwizard commented
There are some interesting features being added, but I wonder if they're appropriate for this particular extension. This extension is named "Camo SSL Image Proxy", but these changes are now supporting other image proxying services. They may be more appropriate in a general "Asset SSL Proxy" extension.

@michaelcullum: Thoughts?

2016-12-11 23:47 UTC, VSEphpbb commented on acp/camosslimageproxy_info.php
> +			'version'	=> '1.1.0',
No versions here

2016-12-11 23:48 UTC, VSEphpbb commented on acp/camosslimageproxy_info.php
> +									 'cat'	=> array('CSIP_EXT')),
Tabs are way off. Please get all the tabs & whitespace sorted out.

2016-12-11 23:50 UTC, VSEphpbb commented on acp/camosslimageproxy_module.php
> +			$sql = 'DELETE FROM ' . $table_prefix . 'camo_domains' . ' WHERE domain_id = ' . $domain_id[0];
Please use `else if` instead of `elseif`, per our coding guidelines.

2016-12-11 23:51 UTC, v12mike commented on acp/camosslimageproxy_module.php
> +		elseif ($request->is_set_post('disable_location_') && $request->variable('disable_location_', array(0 => '')))
The usefulness of disabled state became apparrent after adding the training mode.
For rewriting urls added by other extensions, this extension has to know where to look in the templates.  Cong=figuring this by hand for an arbitrary extension turns out to be a time-consuming task.  The problem is that training mode cannot determine which extension added the url, making it difficult to configure a board for a particular set of extensions.  Having known extensions preconfigured but with their locations disabled allows easy reconfiguration when such an extension is added to a board.

2016-12-11 23:51 UTC, VSEphpbb commented on acp/camosslimageproxy_module.php
> +			$sql = 'DELETE FROM ' . $table_prefix . 'camo_domains' . ' WHERE domain_id = ' . $domain_id[0];
cast `$domain_id[0]` to `(int)`

2016-12-11 23:52 UTC, VSEphpbb commented on acp/camosslimageproxy_module.php
> +			$sql = 'UPDATE ' . $table_prefix . 'camo_locations SET core=0 WHERE location_id=' . $location_id[0];
cat $location_id to (int)

2016-12-11 23:53 UTC, VSEphpbb commented on acp/camosslimageproxy_module.php
> +			$sql = 'UPDATE ' . $table_prefix . 'camo_locations SET core=2 WHERE location_id=' . $location_id[0];
(int) again

2016-12-11 23:53 UTC, VSEphpbb commented on acp/camosslimageproxy_module.php
> +			$sql = 'DELETE FROM ' . $table_prefix . 'camo_locations' . ' WHERE location_id = ' . $location_id[0];
(int) again

2016-12-11 23:54 UTC, VSEphpbb commented on acp/camosslimageproxy_module.php
> +			$location_id = array_keys($request->variable('delete_location_', array(0 => '')));
use `array(0)` instead of `array(0 => '')`

2016-12-11 23:55 UTC, VSEphpbb commented on acp/camosslimageproxy_module.php
> +			$location_id = array_keys($request->variable('delete_location_', array(0 => '')));
Get get `delete_location_` once, and store it in a resuable variable, instead of requesting it multiple times. Same goes for any other similar situations.

2016-12-11 23:55 UTC, VSEphpbb commented on acp/camosslimageproxy_module.php
> +				'domain'		=> $request->variable('camosslimageproxy_adddomain', "", true),
Use single quotes.

2016-12-12 00:07 UTC, v12mike commented on event/listener.php
> +								$this->unhandled_insecure_link(($key == '.')?'headers':$key, $field, $locations);
You misundertand how it works.  It only adds anything to the database in training mode and when the image is fetched for a user with admin privileges , and even then it only adds a location once (irrespective of whether the camo server is running, because it has no way of knowing).

2016-12-12 00:12 UTC, iMattPro requested changes

2016-12-12 00:12 UTC, VSEphpbb commented on composer.json
> +	"version": "1.1.2",
where does 1.1.2 come from? Should be more like 1.1.0-dev IMO.

2016-12-12 00:12 UTC, VSEphpbb commented on composer.json
> +			"role": "Developer"
Please update role to Contributing Developer

2016-12-12 00:12 UTC, VSEphpbb commented on config/services.yml
> +            - %core.root_path%
all % strings need to be quoted too

2016-12-12 00:12 UTC, VSEphpbb commented on event/listener.php
> +define('REGEX_STRING', '#<img [^>]*src="(http://[^"]+)"[^>]*>#'); //define it once here, in csse it needs adjusting
Please don't define constants like this outside of the class (this is a PSR violation). Use class constants instead.

2016-12-12 00:12 UTC, VSEphpbb commented on event/listener.php
> +					$sql = 'UPDATE ' . $this->table_prefix . 'camo_locations SET core=2 WHERE location_id=' . $configured_location['location_id'];
(int)

2016-12-12 00:12 UTC, VSEphpbb commented on event/listener.php
> +		$this->user->add_lang('acp/common');
Not needed

2016-12-12 00:12 UTC, VSEphpbb commented on event/listener.php
> +
empty lines

2016-12-12 00:12 UTC, VSEphpbb commented on event/listener.php
> +		$result = $this->db->sql_query($sql, ONE_MONTH);
There's no need for this ONE_MONTH constant. It only apears in this function so just set a local variable and reuse it instead.

2016-12-12 00:12 UTC, VSEphpbb commented on event/listener.php
> +	public function __construct(\phpbb\config\config $config, \phpbb\db\driver\driver_interface $db, $table_prefix, $auth, $user)
and have a docblock

2016-12-12 00:12 UTC, VSEphpbb commented on migrations/release_1_1_0.php
> +			array('config.add', array('camosslimageproxy_version', '1.1.0')),
Remove this. Versions are not configuration variables. There's no need.

2016-12-12 00:12 UTC, VSEphpbb commented on migrations/release_1_1_0.php
> +			array('config.add', array('camosslimageproxy_proxyaddress', "")),
Single quotes again

2016-12-12 00:12 UTC, VSEphpbb commented on migrations/release_1_1_0.php
> +	public function revert_data()
Remove this. Revert data is automatic.

2016-12-12 00:12 UTC, VSEphpbb commented on migrations/release_1_1_0.php
> +			);
Tabbing off

2016-12-12 10:40 UTC, michaelcullum commented on event/listener.php
> +		$result = $this->db->sql_query($sql, ONE_MONTH);
I'm happy having this constant, but it should be a class constant. It prevents having a magic number here.

2017-02-20 20:28 UTC, DavidIQ commented
There's also conflicts now that need to be resolved.

2017-08-09 05:37 UTC, v12mike commented
I have now decided to maintain this extension as a fork at https://github.com/v12mike/imageredirect rather than attempting to merge into the phpbb extension code base.

2017-08-09 05:37 UTC, closed without merging